<?php

namespace Database\Seeders;

use Carbon\Carbon;
// use Illuminate\Support\Carbon;
use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'id'             => 1,
                'name'           => 'Admin',
                'email'          => 'admin@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 2,
                'name'           => 'Applicant',
                'email'          => 'applicant@email.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 4,
            ],
            [
                'id'             => 3,
                'name'           => 'DFO Kudat',
                'email'          => 'dfokudat@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 4,
                'name'           => 'KPPM KK 1',
                'email'          => 'kppmkk1@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 5,
                'name'           => 'Financial Officer KK',
                'email'          => 'fokk@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 6,
                'name'           => 'Viewer',
                'email'          => 'viewer@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 7,
                'name'           => 'DFO Sandakan',
                'email'          => 'dfosandakan@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 8,
                'name'           => 'DFO Tawau',
                'email'          => 'dfotawau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 9,
                'name'           => 'DFO KK',
                'email'          => 'dfokk@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 10,
                'name'           => 'Matthew',
                'email'          => 'matthew@email.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 0,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 3,
            ],
            [
                'id'             => 11,
                'name'           => 'DFO Keningau',
                'email'          => 'dfokeningau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 12,
                'name'           => 'FO Sandakan',
                'email'          => 'fosdk@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 13,
                'name'           => 'KPPM Sandakan 1',
                'email'          => 'kppmsdk1@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 14,
                'name'           => 'KPPM Sandakan 2',
                'email'          => 'kppmsdk2@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 15,
                'name'           => 'KPPM KK 2',
                'email'          => 'kppmkk2@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 16,
                'name'           => 'FO Tawau',
                'email'          => 'fotawau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 17,
                'name'           => 'FO Kudat',
                'email'          => 'fokudat@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 18,
                'name'           => 'FO Keningau',
                'email'          => 'fokeningau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 19,
                'name'           => 'Applicant 2',
                'email'          => 'applicant2@email.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2,
            ],
            [
                'id'             => 20,
                'name'           => 'Applicant 3',
                'email'          => 'applicant3@email.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 1,
            ],
            [
                'id'             => 21,
                'name'           => 'PPW Tawau',
                'email'          => 'ppwtawau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 22,
                'name'           => 'TPPW Tawau',
                'email'          => 'tppwtawau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 23,
                'name'           => 'ADFO Tawau',
                'email'          => 'adfotawau@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 24,
                'name'           => 'ADFO KK',
                'email'          => 'adfokk@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 25,
                'name'           => 'PPW KK',
                'email'          => 'ppwkk@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
        ];

        User::insert($users);
    }
}
