<?php

namespace Database\Seeders;

use Carbon\Carbon;
// use Illuminate\Support\Carbon;
use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'id'             => 1,
                'name'           => 'Admin',
                'email'          => 'admin@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            //Sandakan
            // Region
            [
                'id'             => 2,
                'name'           => 'Janius Ebin',
                'email'          => 'Janius.Ebin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 3,
                'name'           => 'Hj.Julkifle Bin Hj.Abu Bakar',
                'email'          => 'JulkifleAbu.Bakar@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 4,
                'name'           => 'Isran Bin Maharan',
                'email'          => 'Isran.Maharan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 5,
                'name'           => 'Kassim Jais',
                'email'          => 'Kassim.Jais@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // District
            [
                'id'             => 6,
                'name'           => 'Rosli Siki',
                'email'          => 'Rosli.Siki@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 7,
                'name'           => 'Hj. Asran Hj. Asa',
                'email'          => 'Asran.Asa@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 8,
                'name'           => 'Hj. Hassan Bin Sulaiman',
                'email'          => 'Hassan.Sulaiman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 9,
                'name'           => 'Sahari Sakah',
                'email'          => 'Sahari.Sakah@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 10,
                'name'           => 'Sarail Majamin',
                'email'          => 'Sarail.Majamin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
             
            // Telupid
            [
                'id'             => 11,
                'name'           => 'Ag Ismail Ag Tuah',
                'email'          => 'AgIsmail.AgTuah@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 12,
                'name'           => 'Widi Saradin',
                'email'          => 'Widi.Saradin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 13,
                'name'           => 'David Kawayan',
                'email'          => 'David.Kawayan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 14,
                'name'           => 'Nasri Lamiting',
                'email'          => 'Nasri.Lamiting@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Deramakot
            [
                'id'             => 15,
                'name'           => 'Johny Kissing @ John',
                'email'          => 'Johny.kissing@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 16,
                'name'           => 'Jarius Bin Titin',
                'email'          => 'Jarius.titin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 17,
                'name'           => 'Edward Thomas',
                'email'          => 'Edward.thomaas@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 18,
                'name'           => 'Jaimi Mujit',
                'email'          => 'Jaimi.mujit@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Beluran 
            [
                'id'             => 19,
                'name'           => 'Ag Mohd Adzrul Bin Ag Ahmad',
                'email'          => 'MohdAdzrul.Ahmad@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 20,
                'name'           => 'Markus Salutan',
                'email'          => 'Markus.Salutan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 21,
                'name'           => 'Ahmad Bin Kabulai',
                'email'          => 'Ahmad.Kabulai@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 22,
                'name'           => 'Ahmad Bin Jimadi',
                'email'          => 'Ahmad.Jimadi@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 23,
                'name'           => 'Mohamad Salleh Bin Enting',
                'email'          => 'MohdSalleh.Enting@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Tongod
            [
                'id'             => 24,
                'name'           => 'Abdul Jamal Bin Ibrahim',
                'email'          => 'AbdJamal.Ibrahim@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 25,
                'name'           => 'Richard Madanan',
                'email'          => 'Richard.madanan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 26,
                'name'           => 'Ag. Omar Ali Manggong',
                'email'          => 'AgKuOmarAli.Manggong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 27,
                'name'           => 'Rosman Mejan',
                'email'          => 'Rosman.Mejan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 28,
                'name'           => 'Kim Ann Kim Yong',
                'email'          => 'KimAnn.KimYong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Kinabatangan
            [
                'id'             => 29,
                'name'           => 'Jamain Alias',
                'email'          => 'Jamain.Alias@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 30,
                'name'           => 'Ladwin Ruki',
                'email'          => 'Ladwin.Ruki@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 31,
                'name'           => 'Yusri Boong',
                'email'          => 'Yusri.Boong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 32,
                'name'           => 'Abdul Rahman Abdullah',
                'email'          => 'Abdulrahman.Abdullah@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 33,
                'name'           => 'Rio Peter Gantulik',
                'email'          => 'Riopeter.Gatulik@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Sandakan FO
            [
                'id'             => 34,
                'name'           => 'Dzulkefli Bin Sanip',
                'email'          => 'Dzulkefli.Sanip@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Kota Kinabalu
            // Region
            [
                'id'             => 35,
                'name'           => 'Hj. Mohd. Nasir Hj. Ag. Suman',
                'email'          => 'MohdNasir.AgSuman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 36,
                'name'           => 'Ismail Hj. Aluwisos',
                'email'          => 'Ismail.Aluwisos@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // FO
            [
                'id'             => 37,
                'name'           => 'Hazlina Binti Zaini',
                'email'          => 'Hazlina.Zaini@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // District
            [
                'id'             => 38,
                'name'           => 'Christopher Matunjau',
                'email'          => 'Christopher.Matunjau@Sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 39,
                'name'           => 'Rudziah Binti Abdul Ghani',
                'email'          => 'Rudziah.AbdGhani@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 40,
                'name'           => 'Jasni Bin Rapiee',
                'email'          => 'jasni.Rapiee@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 41,
                'name'           => 'Abdul Rahman bin Mohd. Jari',
                'email'          => 'RahmanMohd.Jari@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Ranau
            [
                'id'             => 42,
                'name'           => 'Suib Basri',
                'email'          => 'suib.basri@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 43,
                'name'           => 'Alexander Geivasius',
                'email'          => 'alexander.Geivasius@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 44,
                'name'           => 'Dainold Yudat',
                'email'          => 'dainold.yudot@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 45,
                'name'           => 'Januit Oson',
                'email'          => 'Jenuit.oson@sabh.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Sipitang
            [
                'id'             => 46,
                'name'           => 'George Angampun',
                'email'          => 'george.angampun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 47,
                'name'           => 'De-Almeida Galima Yukong',
                'email'          => 'DeAlmeidaYukong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 48,
                'name'           => 'Yunus Bin Mutalip',
                'email'          => 'Yunus.Mutalip@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Beaufort
            [
                'id'             => 49,
                'name'           => 'Salleh Intang',
                'email'          => 'salleh.intang@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 50,
                'name'           => 'Vallentine Sebastian',
                'email'          => 'valentine.Sebastian@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Keningau
            // Region
            [
                'id'             => 51,
                'name'           => 'Ismailey Ismail',
                'email'          => 'Ismailey.Ismail@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 52,
                'name'           => 'Magandi Junaid',
                'email'          => 'Magandi.Junaid@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 53,
                'name'           => 'Mazlan Azman',
                'email'          => 'Mazlan.Azman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 54,
                'name'           => 'Jaimi Anggilas',
                'email'          => 'Jaimi.Anggilas@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // FO
            [
                'id'             => 55,
                'name'           => 'Mohd Ramzi Mohd Yusof',
                'email'          => 'MohdRamzi.MohdYusof@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // District
            [
                'id'             => 56,
                'name'           => 'Nerbert Nasly',
                'email'          => 'Nerbert.Nasly@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 57,
                'name'           => 'Clarice Vitalis Alliun',
                'email'          => 'Clarice.Vitalisaliun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 58,
                'name'           => 'Mohd Faizal Basirin',
                'email'          => 'Faizal.Basirin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 59,
                'name'           => 'Wihimus Muis',
                'email'          => 'Wihimus.Muis@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Tibow
            [
                'id'             => 60,
                'name'           => 'Jaimie Gampawi',
                'email'          => 'Jaimie.Gampawi@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 61,
                'name'           => 'Alexius Pius',
                'email'          => 'Alexius.Pius@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 62,
                'name'           => 'Anselmus Pedro',
                'email'          => 'Anselmus.Pedro@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 63,
                'name'           => 'Jen Laduk',
                'email'          => 'Jen.Laduk@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Nabawan
            [
                'id'             => 64,
                'name'           => 'Henry Ladsou',
                'email'          => 'Henry.Ladsou@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 65,
                'name'           => 'Rhymie Abd Rahman',
                'email'          => 'Rhymie.BABDRahman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            [
                'id'             => 66,
                'name'           => 'Yassin Jimbun',
                'email'          => 'Yassin.Jimbun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 67,
                'name'           => 'Junaidi Udut',
                'email'          => 'Junaidi.Udut@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 68,
                'name'           => 'Leroy Goidim',
                'email'          => 'Leroy.Goidim@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Sook
            [
                'id'             => 69,
                'name'           => 'Nessesius Nasir',
                'email'          => 'Nessesius.Nasir@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 70,
                'name'           => 'Bonaventure Oliver Boyou',
                'email'          => 'Bonaventure.Oliver@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 71,
                'name'           => 'Johnny Raymond',
                'email'          => 'Johnny.Raymond@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 72,
                'name'           => 'Victor Agadius',
                'email'          => 'Victor.Agadius@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 73,
                'name'           => 'Richard Goumin',
                'email'          => 'Richard.Goumin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Tenom
            [
                'id'             => 74,
                'name'           => 'Harry Francis Ikok',
                'email'          => 'Harry.FIkok@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 75,
                'name'           => 'Harun Daloh',
                'email'          => 'Haron.Daloh@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 76,
                'name'           => 'Richard Lazanga',
                'email'          => 'Richard.Lazanga@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 77,
                'name'           => 'Ricky Sharif',
                'email'          => 'Ricky.Sharif@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Tambunan
            [
                'id'             => 78,
                'name'           => 'Afifuddin Jadin',
                'email'          => 'Afifuddin.Jadin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 79,
                'name'           => 'Hj Zulkifi Lahab',
                'email'          => 'Zulkifli.Lahab@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 80,
                'name'           => 'Edmund Attiu',
                'email'          => 'Edmund.Attiu@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Kudat
            // Region
            [
                'id'             => 81,
                'name'           => 'Zainuden Jimbun',
                'email'          => 'Zainuden.Jimbun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 82,
                'name'           => 'Chrismon Mintu',
                'email'          => 'Chrismon.Mintu@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 83,
                'name'           => 'Haslan bin pencil',
                'email'          => 'Haslan.Pencil.sabah@gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // FO
            [
                'id'             => 84,
                'name'           => 'Nurliana Binti Jamil',
                'email'          => 'Nurliana.Jamil@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // District
            [
                'id'             => 85,
                'name'           => 'Rustum Mison',
                'email'          => 'Rustum.Mison@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 86,
                'name'           => 'Saikol Bin Aya',
                'email'          => 'Saikol.Aya@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 87,
                'name'           => 'Jaludin Bin Urubit',
                'email'          => 'Jaludin.Urubit@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 88,
                'name'           => 'Hilary Duasik',
                'email'          => 'Hilary.Duasik@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 89,
                'name'           => 'Bigwaison Rudini',
                'email'          => 'Bigwaison.Rudini@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
                                                                        
            // Kota Belud
            [
                'id'             => 90,
                'name'           => 'Zuridah N. Jeragan',
                'email'          => 'Zuridahnorfarizan.jeragan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 91,
                'name'           => 'Wislee Francis @ Jubilee',
                'email'          => 'Wislee.Francis.Jubilee@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 92,
                'name'           => 'Zulfahdly Khalid Khan bin Khalid',
                'email'          => 'ZulfahdlyKhalidKhan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
                                    
            // Kota Marudu
            [
                'id'             => 93,
                'name'           => 'Idris Mustan',
                'email'          => 'Idris.Mustan@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 94,
                'name'           => 'Asiah Rasiman',
                'email'          => 'Asiah.Rasiman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 95,
                'name'           => 'Ahmad Liman',
                'email'          => 'Ahmad.Liman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 96,
                'name'           => 'Jairon Jakiwa',
                'email'          => 'Jairon.Jakiwa@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
                                                
            // Pitas
            [
                'id'             => 97,
                'name'           => 'Norahmad bin Jumain',
                'email'          => 'Norahmad.Jumain@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 98,
                'name'           => 'Fadzil D Moksin JR',
                'email'          => 'Fadzil.Moksin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 99,
                'name'           => 'Peter Sumpit',
                'email'          => 'peter.sumpit@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 100,
                'name'           => 'Dennis Justin Mark',
                'email'          => 'Dennis.Justin.Mark@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            // Tawau
            // Region
            [
                'id'             => 101,
                'name'           => 'Sofiean Mohd Saibi',
                'email'          => 'Sofien.MohdSaibi@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 102,
                'name'           => 'Noordin Musa',
                'email'          => 'Noordin.Musa@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 103,
                'name'           => 'Jeanetry James',
                'email'          => 'Jeanetry.James@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 104,
                'name'           => 'Joe Benjamin Leong',
                'email'          => 'Joe.BenjaminLeong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // FO
            [
                'id'             => 105,
                'name'           => 'Mohamad Zarrin Jafri',
                'email'          => 'MohdZarrin.Jafri@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // District
            [
                'id'             => 106,
                'name'           => 'Mohd Arapa Lamuda',
                'email'          => 'MohdArapa.Lamuda@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 107,
                'name'           => 'Kee Nooridayu Mohd Ayub',
                'email'          => 'Nooridayu.MohdAyub@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 108,
                'name'           => 'Rosdin Abd. Rahman',
                'email'          => 'Roslin.AbdRahman@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 109,
                'name'           => 'Magumba @ Patiroi',
                'email'          => 'AbdMajid.Patiroi@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
                                                            
            // Kalabakan
            [
                'id'             => 110,
                'name'           => 'Mohd. Azmi bin Mohd Yazid @ Pajit',
                'email'          => 'MohdAzmi.Yazid@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 111,
                'name'           => 'Ag. Ku Mohd Ridzwan Pg. Abd Razak',
                'email'          => 'AwangkuRidzwanPg.Razak@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 112,
                'name'           => 'David Shagun',
                'email'          => 'David.Shagun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 113,
                'name'           => 'Yusri Yusof',
                'email'          => 'Yusri.Yusof@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 114,
                'name'           => 'Peter Lumambai',
                'email'          => 'Peter.lumambai@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 115,
                'name'           => 'Judon Lamiting',
                'email'          => 'Judon.Lamiting@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Serudong
            [
                'id'             => 116,
                'name'           => 'Awangku Effendy Pg. Mahmud',
                'email'          => 'AgEffendy.PgMahmud@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 117,
                'name'           => 'Jory Julhani',
                'email'          => 'Jory.Julhani@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 118,
                'name'           => 'Mohd Hadi Jakarulah',
                'email'          => 'MohdHadi.Jakarulah@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 119,
                'name'           => 'Wilfred Pius',
                'email'          => 'Wilfred.Pius@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Kunak
            [
                'id'             => 120,
                'name'           => 'Adrian Rawlenes',
                'email'          => 'Adrian.Rawlenes@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 121,
                'name'           => 'Suriansa A. Kadir',
                'email'          => 'Suriansa.AbdKadir@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 122,
                'name'           => 'Suzali Abd. Ben',
                'email'          => 'Suzali.AbdBen@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 123,
                'name'           => 'Nasari Sahak',
                'email'          => 'Nasari.Sahak@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 124,
                'name'           => 'Vinson Kandi',
                'email'          => 'Vinson.Kandi@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Semporna
            [
                'id'             => 125,
                'name'           => 'Abdul Hamid Muhamad Ali',
                'email'          => 'AbdHamid.MohdAli@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 126,
                'name'           => 'Jintul Tiansun',
                'email'          => 'Jintul.Tiansun@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 127,
                'name'           => 'Suhaimi Mohid',
                'email'          => 'Suhaimi.Mohid@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 128,
                'name'           => 'Yurin Dailit',
                'email'          => 'Yurin.Dailit@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            // Lahad Datu
            [
                'id'             => 129,
                'name'           => 'Osman H. Bangkong',
                'email'          => 'Osman.Bangkong@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 130,
                'name'           => 'Geungnong Ah Jing',
                'email'          => 'Geungnong.AhJing@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 131,
                'name'           => 'Rayner George',
                'email'          => 'Rayner.George@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            [
                'id'             => 132,
                'name'           => 'Harum Benahima',
                'email'          => 'Harum.Benahima@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'), 
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            

            // Applicants
            // Bornion Timber
            [
                'id'             => 133,
                'name'           => 'Adgoh94',
                'email'          => 'adgoh94@gmail.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2095,
            ],
            // TSH
            [
                'id'             => 134,
                'name'           => 'TSH sdkforestry',
                'email'          => 'sdkforestry@tsh.com.my',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 3129,
            ],
            // KTS Plantation
            [
                'id'             => 135,
                'name'           => 'KTSP',
                'email'          => 'ktsplantation@gmail.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 3594,
            ],
            // Timberwell
            [
                'id'             => 136,
                'name'           => 'William Jomiu',
                'email'          => 'williamjomiu@gmail.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 3113,
            ],

            // Adzam Surianiaga sdn bhd
            [
                'id'             => 137,
                'name'           => 'Tsin Fei Yee',
                'email'          => 'vinnetsin@gmail.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2056,
            ],
            
            // Testing Company
            [
                'id'             => 138,
                'name'           => 'Applicant',
                'email'          => 'applicant@email.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 1,
            ],
            


            // Missing internal Users
            // Sandakan KPPMs
            [
                'id'             => 139,
                'name'           => 'Roddey Ariffin',
                'email'          => 'Roddey.Ariffin@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            // Testing Company
            [
                'id'             => 140,
                'name'           => 'Safri Merami',
                'email'          => 'Safri.Merami@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],



            [
                'id'             => 141,
                'name'           => 'Top Quantum',
                'email'          => 'TopQuantum@rakanrimba.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 3123,
            ],

            [
                'id'             => 142,
                'name'           => 'First Green World',
                'email'          => 'firstgreenworld@rakanrimba.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2172,
            ],

            [
                'id'             => 143,
                'name'           => 'PesonaMajukaya',
                'email'          => 'PesonaMajukaya@rakanrimba.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2534,
            ],

            [
                'id'             => 144,
                'name'           => 'Bornion Timber',
                'email'          => 'btlogproduction@gmail.com',
                'type'           => 'external',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => 2095,
            ],
            
            
            [
                'id'             => 145,
                'name'           => 'Bernard Valentine',
                'email'          => 'Bernard.Valentine@sabah.gov.my',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],

            [
                'id'             => 146,
                'name'           => 'Hammer Admin',
                'email'          => 'hadmin@email.com',
                'type'           => 'internal',
                'password'       => bcrypt('password'),
                'is_activated'   => 1,
                'remember_token' => null,
                'email_verified_at' => Carbon::now(),
                'licensee_id'   => null,
            ],
            
            

        ];

        User::insert($users);
    }
}
